version: '3.8'

services:
  web:
    build: .
    container_name: zender-web
    ports:
      - "8080:80"
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./system:/var/www/html/system
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: zender-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: zender_db
      MYSQL_USER: zender_user
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
