name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t smspilot:ci .

      - name: List files in build context
        run: |
          ls -l

      # Optionally push to a registry if you add secrets and uncomment below
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push Docker image
      #   run: |
      #     docker tag smspilot:ci yourdockerhub/smspilot-sms-gateway:latest
      #     docker push yourdockerhub/smspilot-sms-gateway:latest
